# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-07 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spec',
            field=models.CharField(max_length=30, verbose_name='商品规格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=40, verbose_name='商品名称'),
        ),
    ]
